<?php if (count($elements[0]) > 1) { ?>
    <nav>
        <ul class="pagination">
            <?php for ($i = 0; $i < count($elements[0]); $i++) { ?>
                <!--        {% if element is string %}-->
                <!--        <li class="disabled"><span>{{ element }}</span></li>-->
                <!--        {% endif %}-->
                <!---->
                <!--        {% if element is iterable %}-->
                <!--        {% for page, url in element %}-->
                <!--        {% if page == paginator.currentPage() %}-->
                <!--        <li class="active"><span>{{ page }}</span></li>-->
                <!--        {% else %}-->
                <!--        <li><a href="{{ url }}">{{ page }}</a></li>-->
                <!--        {% endif %}-->
                <!--        {% endfor %}-->
                <!--        {% endif %}-->

                <?php if (isset($elements[0][$i])) { ?>
                    <li class="page-item">
                        <a href="<?= $elements[0][$i] ?>" class="page-link"><?= $i + 1 ?></a>
                    </li>
                <?php } else { ?>
                    <li class="page-item active">
                        <a href="javascript:void(0)" class="page-link"><?= $i + 1 ?></a>
                    </li>
                <?php } ?>
            <?php } ?>
        </ul>
    </nav>
<?php } ?>