<?php include "layout/admin-header.phtml" ?>
    <style>
        .description-group .ck-editor__editable {
            height: 300px;
        }

        .features-group .ck-editor__editable {
            height: 200px;
        }
    </style>
    <form method="post" action="/admin/products<?= $mode === 'add' ? '' : ('/' . $product->id) ?>">
        <div class="clearfix admin-header">
            <h1>Thêm sản phẩm mới
                <a href="/admin/products/add">
                    <button type="submit" class="btn btn-primary">Lưu lại</button>
                </a>
            </h1>
        </div>
        <div class="row">
            <div class="col-sm-8">
                <div class="form-group row">
                    <div class="col-sm-12">
                        <input type="text" class="form-control form-control-lg" id="name" name="name"
                               placeholder="Tên sản phẩm" value="<?= $product->name ?>">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="" class="col-sm-2 col-form-label">Giá</label>
                    <div class="col-sm-10">
                        <div class="row">
                            <div class="col-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="price" placeholder="Giá chính thức"
                                           value="<?= $product->price ?>">
                                    <div class="input-group-append">
                                        <span class="input-group-text">VND</span>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="input-group">
                                    <input type="text" class="form-control" name="saleprice"
                                           placeholder="Giá khuyến mãi" value="<?= $product->saleprice ?>">
                                    <div class="input-group-append">
                                        <span class="input-group-text">VND</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group row description-group">
                    <label for="" class="col-sm-2 col-form-label">Mô tả</label>
                    <div class="col-sm-10">
                        <textarea name="description" class="ck-area"><?= $product->description ?></textarea>
                    </div>
                </div>
                <div class="form-group row features-group">
                    <label for="" class="col-sm-2 col-form-label">Tính năng</label>
                    <div class="col-sm-10">
                        <textarea name="features" class="ck-area"><?= $product->features ?></textarea>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="card mb-3">
                    <div class="card-header">Nhóm sản phẩm</div>
                    <div class="card-body">
                        <dl>
                            <?php foreach ($categories as $category) { ?>
                                <dd class="form-check">
                                    <input type="radio" class="form-check-input" name="category_id"
                                           value="<?= $category->id ?>" <?= ($category->id === $product->category_id) ? 'checked' : '' ?>>
                                    <label for="" class="form-check-label"><?= $category->name ?></label>
                                </dd>
                            <?php } ?>
                        </dl>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header">Quản lý kho hàng</div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="">SKU</label>
                            <input type="text" class="form-control" name="sku" value="<?= $product->sku ?>" placeholder="SKU">
                        </div>
                        <div class="form-group">
                            <label for="">Số lượng hàng trong kho</label>
                            <input type="text" class="form-control" name="sku" value="<?= $product->stock ?>" placeholder="Số lượng hàng trong kho">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.1/classic/ckeditor.js"></script>
    <script>
        document.querySelectorAll('.ck-area').forEach(ck => {
            ClassicEditor
                .create(ck)
                .then(editor => {
                    console.log(editor);
                }).catch(error => {
                console.error(error);
            })
        })
    </script>
<?php include "layout/admin-footer.phtml";
