<?php include "layout/admin-header.phtml" ?>
    <div class="clearfix">
        <h1>Danh sách sản phẩm
            <a href="/admin/products/add" class="btn btn-primary" role="button">Thêm sản phẩm</a>
        </h1>
    </div>
<?php ?>
<?php if ($messages) foreach ( $messages as $message ) { ?>
    <div class="alert alert-success" role="alert"><?=$message?></div>
<?php } ?>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Tên sản phẩm</th>
            </tr>
            </thead>
            <tbody>
			<?php foreach ( $products as $product ) { ?>
                <tr>
                    <th scope="row"><?=$product->ID?></th>
                    <td><?=$product->name?></td>
                </tr>
			<?php } ?>
            </tbody>
        </table>
    </div>
<?php include "layout/admin-footer.phtml";
