<?php include "layout/admin-header.phtml" ?>
    <style>
        .description-group .ck-editor__editable {
            height: 300px;
        }

        .features-group .ck-editor__editable {
            height: 200px;
        }
    </style>
    <form action="">
        <div class="clearfix">
            <h1>Thêm sản phẩm mới
                <a href="/admin/products/add">
                    <button class="btn btn-primary">Lưu lại</button>
                </a>
            </h1>
        </div>
		<?php ?>
        <div class="form-group row">
            <label for="name" class="col-sm-2 col-form-label col-form-label-lg">Ten san pham</label>
            <div class="col-sm-10">
                <input type="text" class="form-control form-control-lg" id="name" name="name"
                       placeholder="Ten san pham">
            </div>
        </div>
        <div class="form-group row">
            <label for="" class="col-sm-2 col-form-label">Gia</label>
            <div class="col-sm-10">
                <div class="row">
                    <div class="col-6">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Giá chính thức">
                            <div class="input-group-addon">₫</div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Giá khuyến mãi">
                            <div class="input-group-addon">₫</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group row description-group">
            <label for="" class="col-sm-2 col-form-label">Mo ta</label>
            <div class="col-sm-10">
                <textarea name="description" class="ck-area"></textarea>
            </div>
        </div>
        <div class="form-group row features-group">
            <label for="" class="col-sm-2 col-form-label">Tinh nang</label>
            <div class="col-sm-10">
                <textarea name="features" class="ck-area"></textarea>
            </div>
        </div>
    </form>
    <script src="https://cdn.ckeditor.com/ckeditor5/1.0.0-alpha.1/classic/ckeditor.js"></script>
    <script>
        document.querySelectorAll('.ck-area').forEach(ck => {
            ClassicEditor
                .create(ck)
                .then(editor => {
                    console.log(editor);
                }).catch(error => {
                console.error(error);
            })
        })
    </script>
<?php include "layout/admin-footer.phtml";
