<?php

include "layout/admin-header.phtml" ?>
    <style>
        .table-responsive td .media img{
            width: 60px;
        }
    </style>
    <div class="clearfix admin-header">
        <h1>Danh sách sản phẩm
            <span class="badge badge-secondary"><?= $site['productCount'] ?></span>
            <a href="/admin/products/add" class="btn btn-primary" role="button">Thêm sản phẩm</a>
        </h1>
    </div>
<?php ?>
<?php if ($messages) foreach ($messages as $message) { ?>
    <div class="alert alert-success" role="alert"><?= $message ?></div>
<?php } ?>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Tên sản phẩm</th>
                <th>Giá sản phẩm</th>
                <th>Kho hàng</th>
                <th>Nhóm</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($products as $product) { ?>
                <tr>
                    <th scope="row"><?= $product->id ?></th>
                    <td>
                        <div class="media">
                            <img src="<?= $product->image ?>" alt="" class="border mr-3">
                            <div class="media-body">
                                <strong><a href="/admin/products/<?= $product->id ?>"><?= $product->name ?></a></strong>
                            </div>
                        </div>
                    </td>
                    <td>
                        <?php if ($product->saleprice !== null) { ?>
                            <del class="text-muted"><?= $product->price ?> VND</del>
                            <br>
                            <u><?= $product->saleprice ?> VND</u>
                        <?php } else { ?>
                            <?= $product->price ?> VND
                        <?php } ?>
                    </td>
                    <td>
                        <?php if ($product->stock > 0) { ?>
                            Còn <strong class="text-success"><?=$product->stock?></strong> sản phẩm
                        <?php } else { ?>
                            <span class="text-muted">Hết hàng</span>
                        <?php } ?>
                    </td>
                    <td><?= $product->category->name ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
<?php include "layout/admin-footer.phtml";
