<?php include "layout/admin-header.phtml" ?>
    <div class="clearfix">
        <h1>Danh sách sản phẩm
            <a href="/admin/products/add" class="btn btn-primary" role="button">Thêm sản phẩm</a>
        </h1>
    </div>
<?php ?>
<?php if ($messages) foreach ($messages as $message) { ?>
    <div class="alert alert-success" role="alert"><?= $message ?></div>
<?php } ?>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Tên sản phẩm</th>
                <th>Giá sản phẩm</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($products as $product) { ?>
                <tr>
                    <th scope="row"><?= $product->id ?></th>
                    <td><strong><a href="/admin/products/<?= $product->id ?>"><?= $product->name ?></a></strong></td>
                    <td><?= $product->price ?></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
<?php include "layout/admin-footer.phtml";
