<?php include 'layout/header.phtml' ?>

    <div class="container mt-5">
        <h2>Giỏ hàng</h2>
        <?php if ($count === 0) { ?>
            <div class="text-center pt-5 mb-5">
                <p class="text-muted">Giỏ hàng rỗng :)</p>
                <p>
                    <a href="<?= route('index') ?>" class="btn btn-secondary">Quay lại trang chủ</a>
                </p>
            </div>
        <?php } else { ?>
            <div class="table-responsive pt-5">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Sản phẩm</th>
                        <th>Số lượng</th>
                        <th>Thành tiền</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <td colspan="2"><h5>Tổng số tiền</h5></td>
                        <td>
                            <h5 class="text-success"><?= $totalAmount ?> VND</h5>
                        </td>
                        <td></td>
                    </tr>
                    </tfoot>
                    <tbody>
                    <?php foreach ($items as $id => $item) { ?>
                        <tr class="cart-item">
                            <td>
                                <div class="media">
                                    <img src="<?= $item['product']->image ?>" alt="" class="border mr-3">
                                    <div class="media-body">
                                        <strong><?= $item['product']->name ?></strong>
                                    </div>
                                </div>
                            </td>
                            <td>
                                <?= $item['quantity'] ?>
                            </td>
                            <td>
                                <?= $item['amount'] ?> VND
                            </td>
                            <td>
                                <form action="<?= route('cart.remove', ['id' => $id]) ?>" method="post">
                                    <input type="hidden" name="_METHOD" value="DELETE"/>
                                    <button type="submit" class="btn btn-danger">
                                        Xóa
                                    </button>
                                </form>
                            </td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>

                <div class="mt-2 mb-5 d-flex justify-content-end">
                    <a href="<?= route('index') ?>" class="btn btn-secondary">Quay lại trang chủ</a>
                    <form action="<?= route('cart.remove') ?>" method="post">
                        <input type="hidden" name="_METHOD" value="DELETE"/>
                        <button type="submit" class="ml-2 btn btn-danger">Làm trống giỏ hàng</button>
                    </form>
                    <div class="ml-2 btn btn-success">Thanh toán</div>
                </div>
            </div>
        <?php } ?>
    </div>

<?php include 'layout/footer.phtml' ?>