<?php include 'layout/header.phtml' ?>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 font-weight-normal"><?= $head['siteTitle'] ?></h1>
            <p class="lead font-weight-normal">And an even wittier subheading to boot. Jumpstart your marketing efforts
                with this example based on Apple's marketing pages.</p>
            <a class="btn btn-outline-secondary" href="#">Coming soon</a>
        </div>
        <div class="product-device box-shadow d-none d-md-block"></div>
        <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
    </div>
    <div class="container mt-5">
        <div class="mb-2 pb-2 text-center section-header">
            <h2 class="border-bottom d-inline-block">Danh mục sản phẩm</h2>
        </div>
        <div class="row">
            <?php foreach ($categories as $category) { ?>
                <div class="col-sm-6">
                    <div class="media box-shadow mb-4 rounded border">
                        <img src="<?= $category->image ?>" alt="" class="w-25">
                        <div class="media-body p-3">
                            <h5><?= $category->name ?></h5>
                            <p class="text-muted"><?= substr($category->description, 0, 100) . '...' ?></p>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
    <div class="container mt-4">
        <div class="mb-2 pb-2 text-center section-header">
            <h2 class="border-bottom d-inline-block">Những sản phẩm mới nhất</h2>
        </div>
        <div class="row">
            <?php foreach ($products as $product) { ?>
                <div class="col-sm-4 mb-5 text-center">
                    <img src="<?= $product->image ?>" alt="" class="mx-auto w-75 d-block rounded-circle mb-4">
                    <h4><?= $product->name ?></h4>
                    <p class="text-muted"><?= substr($product->description, 0, 120) . '...' ?></p>
                    <h5 class="text-success"><?=$product->price?> VND</h5>
                </div>
            <?php } ?>
        </div>
    </div>
<?php include 'layout/footer.phtml' ?>