<?php include 'layout/header.phtml' ?>
<div class="container mt-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="<?= route('index') ?>">Trang chủ</a>
            </li>
            <li class="breadcrumb-item">
                <a href="<?= route('product.list', [], ['cat' => $product->category->id]) ?>"><?= $product->category->name ?></a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <?= $product->name ?>
            </li>
        </ol>
    </nav>
    <section class="product-summary mt-5">
        <div class="row">
            <div class="col-sm-5">
                <img src="<?= url($product->image) ?>" alt="" class="img-fluid">
            </div>
            <div class="col-sm-7">
                <h2>
                    <?= $product->name ?>
                    <?php if ($product->is_sale) { ?>
                        <span class="badge badge-success ml-2">SALE OFF <?= round($product->sale_percentage * 100) ?>
                            %</span>
                    <?php } ?>
                </h2>
                <div class="price <?= $product->is_sale ? 'price-has-sale' : '' ?>">
                    <?php if ($product->is_sale) { ?>
                        <span>
                            <del class="text-muted"><?= $product->price ?> VND</del>
                        </span>
                        <span class="ml-2"><?= $product->saleprice ?> VND</span>
                    <?php } else { ?>
                        <?= $product->price ?> VND
                    <?php } ?>
                </div>
                <hr>
                <p class="text-justify"><?= $product->features ?></p>
                <form action="<?= route('cart.add') ?>" method="POST">
                    <input type="hidden" name="product_id" value="<?= $product->id ?>">
                    <div>
                        <small class="form-text text-muted mb-2">Số lượng</small>
                        <input type="text" class="form-control form-control-lg d-inline w-25" value="1" name="quantity">
                        <button type="submit" class="btn btn-lg btn-success d-inline ml-2" style="margin-top: -3px">
                            <span class="oi oi-cart"></span>
                            Thêm vào giỏ hàng
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </section>
</div>
<?php include 'layout/footer.phtml' ?>
